server:
  port: 18010
  servlet:
    context-path: /demo/

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:logback/logback-spring.xml
  exception-conversion-word: '%wEx'
  level:
    root: info
    com.github.learn17.module.demo: debug
    com.github.learn17.core.db: debug
  file:
    name: ${spring.application.name}.log
    path: ./logs/${spring.application.name}/

pagehelper:
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  auto-dialect: true
  auto-runtime-dialect: true

mybatis:
  type-aliases-package: com.github.learn17.module.demo.domain.*
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

learn17:
  thread-core:
    keep-alive-time: 20000
    thread-name-prefix: learn17-demo-exec-
    capacity: 50