server:
  port: 18012

logging:
  config: classpath:logback/logback-spring.xml
  exception-conversion-word: '%wEx'
  level:
    root: info
  file:
    name: ${spring.application.name}.log
    path: ./logs/${spring.application.name}/